version: "2"
services:
  node1:
    image: akka-cluster
    environment:
      NODE_HOSTNAME: node1
      SEED_NODE1: node1
      SEED_NODE2: node2
      SEED_NODE3: node3
    volumes:
      - ./configs/sandbox/conf:/config/

  node2:
    image: akka-cluster
    environment:
      NODE_HOSTNAME: node2
      SEED_NODE1: node1
      SEED_NODE2: node2
      SEED_NODE3: node3
    volumes:
      - ./configs/sandbox/conf:/config/

  node3:
    image: akka-cluster
    environment:
      NODE_HOSTNAME: node3
      SEED_NODE1: node1
      SEED_NODE2: node2
      SEED_NODE3: node3
    volumes:
      - ./configs/sandbox/conf:/config/